project:
  name: quickstart-linux-utilities
  owner: tonynv@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-2
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  Amazon-Linux2:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      GitRepo: https://github.com/username/quickstart-linux-utilities.git
      TestAMIOS: Amazon-Linux2-HVM
    template: templates/ci_test-master.template.yaml
  Amazon-Linux1:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      GitRepo: https://github.com/username/quickstart-linux-utilities.git
      TestAMIOS: Amazon-Linux-HVM
    template: templates/ci_test-master.template.yaml
  Ubuntu1604:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      GitRepo: https://github.com/username/quickstart-linux-utilities.git
      TestAMIOS: Ubuntu-Server-16.04-LTS-HVM
    template: templates/ci_test-master.template.yaml
