AWSTemplateFormatVersion: 2010-09-09
Description: "CI Stack for Linux Utils"
Metadata:
  LICENSE: 'Apache License, Version 2.0' 
  AUTHOR: 'Tony Vattathil'
  EMAIL: 'tonynv@amazon.com'
Parameters:
  TestAMIOS:
    AllowedValues:
      - Amazon-Linux2-HVM
      - Amazon-Linux-HVM
      - CentOS-7-HVM
      - Ubuntu-Server-14.04-LTS-HVM
      - Ubuntu-Server-16.04-LTS-HVM
      - Ubuntu-Server-18.04-LTS-HVM
      - SUSE-SLES-15-HVM
    Default: Amazon-Linux2-HVM
    Description: The Linux distribution for the AMI to be used for the bastion instances.
    Type: String
  AccessCIDR:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: The IP address range that can be used to access to the EC2 instance
    MaxLength: '18'
    MinLength: '9'
    Type: String
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: id_rsa_aws
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  SubnetId:
    Description: The Public subnet where the ec2 instance will be launched
    Type: AWS::EC2::Subnet::Id
  VPCID:
    Description: The VPC to launch the GitHub Enterprise server
    Type: AWS::EC2::VPC::Id
  BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: 'replace-with-your-staging-bucket'
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-linux-utilities/
    Description: >-
      S3 key prefix where assets are located should end withforward slash (/).
    Type: String
  GitRepo:
    Default: https://github.com/aws-quickstart/quickstart-linux-utilities.git
    Type: String
  GitBranch:
    Default: develop
    Type: String
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      AMZNLINUX2: ami-0064e711cbc7a825e
      AMZNLINUXHVM: ami-0ab3e16f9c414dee7
      CENTOS7HVM: ami-045f38c93733dd48d
      US1604HVM: ami-014cc8d7cb6d26dc8
      US1804HVM: ami-0f6b4f4104d26f399
      SLES15HVM: ami-056ac8ad44e6a7e1f
    ap-northeast-2:
      AMZNLINUX2: ami-02b3330196502d247
      AMZNLINUXHVM: ami-0e1e385b0a934254a
      CENTOS7HVM: ami-06cf2a72dadf92410
      US1604HVM: ami-004b3430b806f3b1a
      US1804HVM: ami-02b4a5559ce53a570
      SLES15HVM: ami-0f81fff879bafe6b8
    ap-south-1:
      AMZNLINUX2: ami-040c7ad0a93be494e
      AMZNLINUXHVM: ami-02913db388613c3e1
      CENTOS7HVM: ami-02e60be79e78fef21
      US1604HVM: ami-0f59afa4a22fad2f0
      US1804HVM: ami-0245841fc4b40e22f
      SLES15HVM: ami-01be89269d32f2a16
    ap-southeast-1:
      AMZNLINUX2: ami-00942d7cd4f3ca5c0
      AMZNLINUXHVM: ami-05c859630889c79c8
      CENTOS7HVM: ami-0b4dd9d65556cac22
      US1604HVM: ami-08b3278ea6e379084
      US1804HVM: ami-07febfdfb4080320e
      SLES15HVM: ami-070356c21596ddc67
    ap-southeast-2:
      AMZNLINUX2: ami-08a74056dfd30c986
      AMZNLINUXHVM: ami-07cc15c3ba6f8e287
      CENTOS7HVM: ami-08bd00d7713a39e7d
      US1604HVM: ami-00d7116c396e73b04
      US1804HVM: ami-04a0f7552cff370ba
      SLES15HVM: ami-0c4245381c67efb39
    ca-central-1:
      AMZNLINUX2: ami-007dbcbce3118978b
      AMZNLINUXHVM: ami-04070f04f450607dc
      CENTOS7HVM: ami-033e6106180a626d0
      US1604HVM: ami-0086bcfbab4b22f60
      US1804HVM: ami-0972a0d3135cf1fc0
      SLES15HVM: ami-0c97d9b588207dad6
    eu-central-1:
      AMZNLINUX2: ami-0f3a43fbf2d3899f7
      AMZNLINUXHVM: ami-010fae13a16763bb4
      CENTOS7HVM: ami-04cf43aca3e6f3de3
      US1604HVM: ami-0062c497b55437b01
      US1804HVM: ami-09356619876445425
      SLES15HVM: ami-05dfd265ea534a3e9
    eu-north-1:
      AMZNLINUX2: ami-0c947472aff72870d
      AMZNLINUXHVM: ami-6a1f9414
      CENTOS7HVM: ami-5ee66f20
      US1604HVM: ami-0ca3b50bc99a41773
      US1804HVM: ami-005bc7d72deb72a3d
      SLES15HVM: ami-0741fa1a008af40ad
    eu-west-1:
      AMZNLINUX2: ami-040ba9174949f6de4
      AMZNLINUXHVM: ami-028188d9b49b32a80
      CENTOS7HVM: ami-0ff760d16d9497662
      US1604HVM: ami-0987ee37af7792903
      US1804HVM: ami-04c58523038d79132
      SLES15HVM: ami-0a58a1b152ba55f1d
    eu-west-2:
      AMZNLINUX2: ami-00e8b55a2e841be44
      AMZNLINUXHVM: ami-04de2b60dd25fbb2e
      CENTOS7HVM: ami-0eab3a90fc693af19
      US1604HVM: ami-05945867d79b7d926
      US1804HVM: ami-00622b440d92e55c0
      SLES15HVM: ami-01497522185aaa4ee
    eu-west-3:
      AMZNLINUX2: ami-05a51ff00c1d77571
      AMZNLINUXHVM: ami-0652eb0db9b20aeaf
      CENTOS7HVM: ami-0e1ab783dc9489f34
      US1604HVM: ami-00c60f4df93ff408e
      US1804HVM: ami-0b70d1460d5c7a299
      SLES15HVM: ami-0f238bd4c6fdbefb0
    sa-east-1:
      AMZNLINUX2: ami-053f8b6627112b46e
      AMZNLINUXHVM: ami-0e2c2c29d8017dd99
      CENTOS7HVM: ami-0b8d86d4bf91850af
      US1604HVM: ami-0fb487b6f6ab53ff4
      US1804HVM: ami-049f5d88d2d436431
      SLES15HVM: ami-0772af912976aa692
    us-east-1:
      AMZNLINUX2: ami-00dc79254d0461090
      AMZNLINUXHVM: ami-00eb20669e0990cb4
      CENTOS7HVM: ami-02eac2c0129f6376b
      US1604HVM: ami-09f9d773751b9d606
      US1804HVM: ami-00a208c7cdba991ea
      SLES15HVM: ami-0b1764f3d7d2e2316
    us-east-2:
      AMZNLINUX2: ami-00bf61217e296b409
      AMZNLINUXHVM: ami-0c64dd618a49aeee8
      CENTOS7HVM: ami-0f2b4fc905b0bd1f1
      US1604HVM: ami-0891395d749676c2e
      US1804HVM: ami-059d836af932792c3
      SLES15HVM: ami-05ea824317ffc0c20
    us-west-1:
      AMZNLINUX2: ami-024c80694b5b3e51a
      AMZNLINUXHVM: ami-0bce08e823ed38bdd
      CENTOS7HVM: ami-074e2d6769f445be5
      US1604HVM: ami-0c0e5a396959508b0
      US1804HVM: ami-0f42d8c4eb586ccf7
      SLES15HVM: ami-00e34a7624e5a7107
    us-west-2:
      AMZNLINUX2: ami-0a85857bfc5345c38
      AMZNLINUXHVM: ami-08d489468314a58df
      CENTOS7HVM: ami-01ed306a12b7d1c96
      US1604HVM: ami-0bbe9b07c5fe8e86e
      US1804HVM: ami-0a7d051a1c4b54f65
      SLES15HVM: ami-0f1e3b3fb0fec0361
  LinuxAMINameMap:
    Amazon-Linux2-HVM:
      Code: AMZNLINUX2
    Amazon-Linux-HVM:
      Code: AMZNLINUXHVM
    CentOS-7-HVM:
      Code: CENTOS7HVM
    Ubuntu-Server-18.04-LTS-HVM:
      Code: US1804HVM
    Ubuntu-Server-16.04-LTS-HVM:
      Code: US1604HVM
    SUSE-SLES-15-HVM:
      Code: SLES15HVM
Conditions:
  GovCloudCondition: !Equals
    - !Ref AWS::Region
    - us-gov-west-1
Resources:
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ec2.amazonaws.com
            Effect: Allow
            Sid: ''
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${BucketName}/${KeyPrefix}*'
                Effect: Allow
          PolicyName: AuthenticatedS3GetObjects
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  InstanceSecurityGroup:
    Properties:
      GroupDescription: 'ssh access to instance'
      SecurityGroupIngress:
        - CidrIp: !Ref AccessCIDR
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref VPCID
    Type: 'AWS::EC2::SecurityGroup'
  LinuxInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      IamInstanceProfile: !Ref RootInstanceProfile
      ImageId: !FindInMap 
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - !FindInMap 
          - LinuxAMINameMap
          - !Ref TestAMIOS
          - Code
      InstanceType: t2.large
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref SubnetId
      UserData: !Base64
          Fn::Sub: 
          - |
            #!/bin/bash -x
            #cfn signaling functions
            echo "[INFO] Start UserData in ${S3Region}";
            yum install git -y || apt-get install -y git

            function cfn_fail
            {
              cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource LinuxInstance
              exit 1
            }

            function cfn_success
            {
              cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource LinuxInstance
              exit 0
            }

            until git clone -b ${GitBranch} ${GitRepo} ; do echo "Retrying"; done
            cd /quickstart-linux-utilities;
            source quickstart-cfn-tools.source;
            qs_update-os || qs_err;
            qs_bootstrap_pip || qs_err " pip bootstrap failed ";
            qs_aws-cfn-bootstrap || qs_err " cfn bootstrap failed ";
            echo "[INFO] Executing config-sets";
            cfn-init -v --stack ${AWS::StackName} --resource LinuxInstance --configsets ec2_bootstrap --region ${AWS::Region} || cfn_fail;
            [ $(qs_status) == 0 ] && cfn_success || cfn_fail
          -  
            S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
    Metadata:
      AWS::CloudFormation::Authentication: 
        S3AccessCreds: 
          type: S3
          buckets: 
            - !Sub ${BucketName}
          roleName: 
            Ref: RootRole
      AWS::CloudFormation::Init:
        configSets:
          ec2_bootstrap:
            - helloworld_cfg
        helloworld_cfg:
          files:
            /tmp/bootstrap.sh:
              source: !Sub
                - >-
                  https://${BucketName}.${S3Region}.amazonaws.com/${KeyPrefix}scripts/print_stdout.sh
                - BucketName: !Ref BucketName
                  S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, !Sub 's3.${AWS::Region}' ]
                  KeyPrefix: !Ref KeyPrefix
              mode: '000755'
              owner: root
              group: root
              command: /tmp/bootstrap.sh 'hello world'
              authentication: S3AccessCreds
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT20M
